// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protos/price/v1/product_price.proto

package price

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductPriceMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CityId        string                 `protobuf:"bytes,2,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductPriceMain) Reset() {
	*x = ProductPriceMain{}
	mi := &file_protos_price_v1_product_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductPriceMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPriceMain) ProtoMessage() {}

func (x *ProductPriceMain) ProtoReflect() protoreflect.Message {
	mi := &file_protos_price_v1_product_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPriceMain.ProtoReflect.Descriptor instead.
func (*ProductPriceMain) Descriptor() ([]byte, []int) {
	return file_protos_price_v1_product_price_proto_rawDescGZIP(), []int{0}
}

func (x *ProductPriceMain) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductPriceMain) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

func (x *ProductPriceMain) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ProductPriceGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CityId        string                 `protobuf:"bytes,2,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductPriceGetReq) Reset() {
	*x = ProductPriceGetReq{}
	mi := &file_protos_price_v1_product_price_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductPriceGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPriceGetReq) ProtoMessage() {}

func (x *ProductPriceGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_price_v1_product_price_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPriceGetReq.ProtoReflect.Descriptor instead.
func (*ProductPriceGetReq) Descriptor() ([]byte, []int) {
	return file_protos_price_v1_product_price_proto_rawDescGZIP(), []int{1}
}

func (x *ProductPriceGetReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductPriceGetReq) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

type ProductPriceListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListParams    *ListParamsSt          `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	ProductIds    []string               `protobuf:"bytes,2,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	CityIds       []string               `protobuf:"bytes,3,rep,name=city_ids,json=cityIds,proto3" json:"city_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductPriceListReq) Reset() {
	*x = ProductPriceListReq{}
	mi := &file_protos_price_v1_product_price_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductPriceListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPriceListReq) ProtoMessage() {}

func (x *ProductPriceListReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_price_v1_product_price_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPriceListReq.ProtoReflect.Descriptor instead.
func (*ProductPriceListReq) Descriptor() ([]byte, []int) {
	return file_protos_price_v1_product_price_proto_rawDescGZIP(), []int{2}
}

func (x *ProductPriceListReq) GetListParams() *ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *ProductPriceListReq) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *ProductPriceListReq) GetCityIds() []string {
	if x != nil {
		return x.CityIds
	}
	return nil
}

type ProductPriceListRep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaginationInfo *PaginationInfoSt      `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*ProductPriceMain    `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductPriceListRep) Reset() {
	*x = ProductPriceListRep{}
	mi := &file_protos_price_v1_product_price_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductPriceListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPriceListRep) ProtoMessage() {}

func (x *ProductPriceListRep) ProtoReflect() protoreflect.Message {
	mi := &file_protos_price_v1_product_price_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPriceListRep.ProtoReflect.Descriptor instead.
func (*ProductPriceListRep) Descriptor() ([]byte, []int) {
	return file_protos_price_v1_product_price_proto_rawDescGZIP(), []int{3}
}

func (x *ProductPriceListRep) GetPaginationInfo() *PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *ProductPriceListRep) GetResults() []*ProductPriceMain {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_protos_price_v1_product_price_proto protoreflect.FileDescriptor

const file_protos_price_v1_product_price_proto_rawDesc = "" +
	"\n" +
	"#protos/price/v1/product_price.proto\x12\x05price\x1a\x1cgoogle/api/annotations.proto\x1a\x1cprotos/price/v1/common.proto\"`\n" +
	"\x10ProductPriceMain\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\acity_id\x18\x02 \x01(\tR\x06cityId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"L\n" +
	"\x12ProductPriceGetReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\acity_id\x18\x02 \x01(\tR\x06cityId\"\x87\x01\n" +
	"\x13ProductPriceListReq\x124\n" +
	"\vlist_params\x18\x01 \x01(\v2\x13.price.ListParamsStR\n" +
	"listParams\x12\x1f\n" +
	"\vproduct_ids\x18\x02 \x03(\tR\n" +
	"productIds\x12\x19\n" +
	"\bcity_ids\x18\x03 \x03(\tR\acityIds\"\x8a\x01\n" +
	"\x13ProductPriceListRep\x12@\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x17.price.PaginationInfoStR\x0epaginationInfo\x121\n" +
	"\aresults\x18\x02 \x03(\v2\x17.price.ProductPriceMainR\aresults2\xbd\x01\n" +
	"\fProductPrice\x12V\n" +
	"\x04List\x12\x1a.price.ProductPriceListReq\x1a\x1a.price.ProductPriceListRep\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/product_price\x12U\n" +
	"\x03Get\x12\x19.price.ProductPriceGetReq\x1a\x17.price.ProductPriceMain\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/product_price/oneB\x11Z\x0f/price/v1;priceb\x06proto3"

var (
	file_protos_price_v1_product_price_proto_rawDescOnce sync.Once
	file_protos_price_v1_product_price_proto_rawDescData []byte
)

func file_protos_price_v1_product_price_proto_rawDescGZIP() []byte {
	file_protos_price_v1_product_price_proto_rawDescOnce.Do(func() {
		file_protos_price_v1_product_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_price_v1_product_price_proto_rawDesc), len(file_protos_price_v1_product_price_proto_rawDesc)))
	})
	return file_protos_price_v1_product_price_proto_rawDescData
}

var file_protos_price_v1_product_price_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_price_v1_product_price_proto_goTypes = []any{
	(*ProductPriceMain)(nil),    // 0: price.ProductPriceMain
	(*ProductPriceGetReq)(nil),  // 1: price.ProductPriceGetReq
	(*ProductPriceListReq)(nil), // 2: price.ProductPriceListReq
	(*ProductPriceListRep)(nil), // 3: price.ProductPriceListRep
	(*ListParamsSt)(nil),        // 4: price.ListParamsSt
	(*PaginationInfoSt)(nil),    // 5: price.PaginationInfoSt
}
var file_protos_price_v1_product_price_proto_depIdxs = []int32{
	4, // 0: price.ProductPriceListReq.list_params:type_name -> price.ListParamsSt
	5, // 1: price.ProductPriceListRep.pagination_info:type_name -> price.PaginationInfoSt
	0, // 2: price.ProductPriceListRep.results:type_name -> price.ProductPriceMain
	2, // 3: price.ProductPrice.List:input_type -> price.ProductPriceListReq
	1, // 4: price.ProductPrice.Get:input_type -> price.ProductPriceGetReq
	3, // 5: price.ProductPrice.List:output_type -> price.ProductPriceListRep
	0, // 6: price.ProductPrice.Get:output_type -> price.ProductPriceMain
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_price_v1_product_price_proto_init() }
func file_protos_price_v1_product_price_proto_init() {
	if File_protos_price_v1_product_price_proto != nil {
		return
	}
	file_protos_price_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_price_v1_product_price_proto_rawDesc), len(file_protos_price_v1_product_price_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_price_v1_product_price_proto_goTypes,
		DependencyIndexes: file_protos_price_v1_product_price_proto_depIdxs,
		MessageInfos:      file_protos_price_v1_product_price_proto_msgTypes,
	}.Build()
	File_protos_price_v1_product_price_proto = out.File
	file_protos_price_v1_product_price_proto_goTypes = nil
	file_protos_price_v1_product_price_proto_depIdxs = nil
}
