// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: protos/etl/v1/etl.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ETLService_Start_FullMethodName  = "/category.ETLService/Start"
	ETLService_Stop_FullMethodName   = "/category.ETLService/Stop"
	ETLService_Status_FullMethodName = "/category.ETLService/Status"
)

// ETLServiceClient is the client API for ETLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ETLServiceClient interface {
	Start(ctx context.Context, in *ETLRequest, opts ...grpc.CallOption) (*ETLResponse, error)
	Stop(ctx context.Context, in *ETLRequest, opts ...grpc.CallOption) (*ETLResponse, error)
	Status(ctx context.Context, in *ETLRequest, opts ...grpc.CallOption) (*ETLResponse, error)
}

type eTLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewETLServiceClient(cc grpc.ClientConnInterface) ETLServiceClient {
	return &eTLServiceClient{cc}
}

func (c *eTLServiceClient) Start(ctx context.Context, in *ETLRequest, opts ...grpc.CallOption) (*ETLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ETLResponse)
	err := c.cc.Invoke(ctx, ETLService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTLServiceClient) Stop(ctx context.Context, in *ETLRequest, opts ...grpc.CallOption) (*ETLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ETLResponse)
	err := c.cc.Invoke(ctx, ETLService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTLServiceClient) Status(ctx context.Context, in *ETLRequest, opts ...grpc.CallOption) (*ETLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ETLResponse)
	err := c.cc.Invoke(ctx, ETLService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ETLServiceServer is the server API for ETLService service.
// All implementations must embed UnimplementedETLServiceServer
// for forward compatibility.
type ETLServiceServer interface {
	Start(context.Context, *ETLRequest) (*ETLResponse, error)
	Stop(context.Context, *ETLRequest) (*ETLResponse, error)
	Status(context.Context, *ETLRequest) (*ETLResponse, error)
	mustEmbedUnimplementedETLServiceServer()
}

// UnimplementedETLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedETLServiceServer struct{}

func (UnimplementedETLServiceServer) Start(context.Context, *ETLRequest) (*ETLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedETLServiceServer) Stop(context.Context, *ETLRequest) (*ETLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedETLServiceServer) Status(context.Context, *ETLRequest) (*ETLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedETLServiceServer) mustEmbedUnimplementedETLServiceServer() {}
func (UnimplementedETLServiceServer) testEmbeddedByValue()                    {}

// UnsafeETLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ETLServiceServer will
// result in compilation errors.
type UnsafeETLServiceServer interface {
	mustEmbedUnimplementedETLServiceServer()
}

func RegisterETLServiceServer(s grpc.ServiceRegistrar, srv ETLServiceServer) {
	// If the following call pancis, it indicates UnimplementedETLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ETLService_ServiceDesc, srv)
}

func _ETLService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ETLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETLServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ETLService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETLServiceServer).Start(ctx, req.(*ETLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETLService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ETLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETLServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ETLService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETLServiceServer).Stop(ctx, req.(*ETLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETLService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ETLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETLServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ETLService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETLServiceServer).Status(ctx, req.(*ETLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ETLService_ServiceDesc is the grpc.ServiceDesc for ETLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ETLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "category.ETLService",
	HandlerType: (*ETLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _ETLService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _ETLService_Stop_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _ETLService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/etl/v1/etl.proto",
}
