// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: protos/store/v1/product_stock.proto

package store

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductStock_List_FullMethodName = "/store.ProductStock/List"
	ProductStock_Get_FullMethodName  = "/store.ProductStock/Get"
)

// ProductStockClient is the client API for ProductStock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductStockClient interface {
	List(ctx context.Context, in *ProductStockListReq, opts ...grpc.CallOption) (*ProductStockListRep, error)
	Get(ctx context.Context, in *ProductStockGetReq, opts ...grpc.CallOption) (*ProductStockMain, error)
}

type productStockClient struct {
	cc grpc.ClientConnInterface
}

func NewProductStockClient(cc grpc.ClientConnInterface) ProductStockClient {
	return &productStockClient{cc}
}

func (c *productStockClient) List(ctx context.Context, in *ProductStockListReq, opts ...grpc.CallOption) (*ProductStockListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductStockListRep)
	err := c.cc.Invoke(ctx, ProductStock_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productStockClient) Get(ctx context.Context, in *ProductStockGetReq, opts ...grpc.CallOption) (*ProductStockMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductStockMain)
	err := c.cc.Invoke(ctx, ProductStock_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductStockServer is the server API for ProductStock service.
// All implementations must embed UnimplementedProductStockServer
// for forward compatibility.
type ProductStockServer interface {
	List(context.Context, *ProductStockListReq) (*ProductStockListRep, error)
	Get(context.Context, *ProductStockGetReq) (*ProductStockMain, error)
	mustEmbedUnimplementedProductStockServer()
}

// UnimplementedProductStockServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductStockServer struct{}

func (UnimplementedProductStockServer) List(context.Context, *ProductStockListReq) (*ProductStockListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProductStockServer) Get(context.Context, *ProductStockGetReq) (*ProductStockMain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedProductStockServer) mustEmbedUnimplementedProductStockServer() {}
func (UnimplementedProductStockServer) testEmbeddedByValue()                      {}

// UnsafeProductStockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductStockServer will
// result in compilation errors.
type UnsafeProductStockServer interface {
	mustEmbedUnimplementedProductStockServer()
}

func RegisterProductStockServer(s grpc.ServiceRegistrar, srv ProductStockServer) {
	// If the following call pancis, it indicates UnimplementedProductStockServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductStock_ServiceDesc, srv)
}

func _ProductStock_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductStockListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductStockServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductStock_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductStockServer).List(ctx, req.(*ProductStockListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductStock_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductStockGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductStockServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductStock_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductStockServer).Get(ctx, req.(*ProductStockGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductStock_ServiceDesc is the grpc.ServiceDesc for ProductStock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductStock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "store.ProductStock",
	HandlerType: (*ProductStockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ProductStock_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ProductStock_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/store/v1/product_stock.proto",
}
