// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protos/store/v1/product_stock.proto

package store

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductStockMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CityId        string                 `protobuf:"bytes,2,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	Value         int64                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductStockMain) Reset() {
	*x = ProductStockMain{}
	mi := &file_protos_store_v1_product_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductStockMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStockMain) ProtoMessage() {}

func (x *ProductStockMain) ProtoReflect() protoreflect.Message {
	mi := &file_protos_store_v1_product_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStockMain.ProtoReflect.Descriptor instead.
func (*ProductStockMain) Descriptor() ([]byte, []int) {
	return file_protos_store_v1_product_stock_proto_rawDescGZIP(), []int{0}
}

func (x *ProductStockMain) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductStockMain) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

func (x *ProductStockMain) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ProductStockGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CityId        string                 `protobuf:"bytes,2,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductStockGetReq) Reset() {
	*x = ProductStockGetReq{}
	mi := &file_protos_store_v1_product_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductStockGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStockGetReq) ProtoMessage() {}

func (x *ProductStockGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_store_v1_product_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStockGetReq.ProtoReflect.Descriptor instead.
func (*ProductStockGetReq) Descriptor() ([]byte, []int) {
	return file_protos_store_v1_product_stock_proto_rawDescGZIP(), []int{1}
}

func (x *ProductStockGetReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductStockGetReq) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

type ProductStockListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListParams    *ListParamsSt          `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	ProductIds    []string               `protobuf:"bytes,2,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	CityIds       []string               `protobuf:"bytes,3,rep,name=city_ids,json=cityIds,proto3" json:"city_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductStockListReq) Reset() {
	*x = ProductStockListReq{}
	mi := &file_protos_store_v1_product_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductStockListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStockListReq) ProtoMessage() {}

func (x *ProductStockListReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_store_v1_product_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStockListReq.ProtoReflect.Descriptor instead.
func (*ProductStockListReq) Descriptor() ([]byte, []int) {
	return file_protos_store_v1_product_stock_proto_rawDescGZIP(), []int{2}
}

func (x *ProductStockListReq) GetListParams() *ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *ProductStockListReq) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *ProductStockListReq) GetCityIds() []string {
	if x != nil {
		return x.CityIds
	}
	return nil
}

type ProductStockListRep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaginationInfo *PaginationInfoSt      `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*ProductStockMain    `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductStockListRep) Reset() {
	*x = ProductStockListRep{}
	mi := &file_protos_store_v1_product_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductStockListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStockListRep) ProtoMessage() {}

func (x *ProductStockListRep) ProtoReflect() protoreflect.Message {
	mi := &file_protos_store_v1_product_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStockListRep.ProtoReflect.Descriptor instead.
func (*ProductStockListRep) Descriptor() ([]byte, []int) {
	return file_protos_store_v1_product_stock_proto_rawDescGZIP(), []int{3}
}

func (x *ProductStockListRep) GetPaginationInfo() *PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *ProductStockListRep) GetResults() []*ProductStockMain {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_protos_store_v1_product_stock_proto protoreflect.FileDescriptor

const file_protos_store_v1_product_stock_proto_rawDesc = "" +
	"\n" +
	"#protos/store/v1/product_stock.proto\x12\x05store\x1a\x1cgoogle/api/annotations.proto\x1a\x1cprotos/store/v1/common.proto\"`\n" +
	"\x10ProductStockMain\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\acity_id\x18\x02 \x01(\tR\x06cityId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\"L\n" +
	"\x12ProductStockGetReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\acity_id\x18\x02 \x01(\tR\x06cityId\"\x87\x01\n" +
	"\x13ProductStockListReq\x124\n" +
	"\vlist_params\x18\x01 \x01(\v2\x13.store.ListParamsStR\n" +
	"listParams\x12\x1f\n" +
	"\vproduct_ids\x18\x02 \x03(\tR\n" +
	"productIds\x12\x19\n" +
	"\bcity_ids\x18\x03 \x03(\tR\acityIds\"\x8a\x01\n" +
	"\x13ProductStockListRep\x12@\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x17.store.PaginationInfoStR\x0epaginationInfo\x121\n" +
	"\aresults\x18\x02 \x03(\v2\x17.store.ProductStockMainR\aresults2\xbd\x01\n" +
	"\fProductStock\x12V\n" +
	"\x04List\x12\x1a.store.ProductStockListReq\x1a\x1a.store.ProductStockListRep\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/product_stock\x12U\n" +
	"\x03Get\x12\x19.store.ProductStockGetReq\x1a\x17.store.ProductStockMain\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/product_stock/oneB\x11Z\x0f/store/v1;storeb\x06proto3"

var (
	file_protos_store_v1_product_stock_proto_rawDescOnce sync.Once
	file_protos_store_v1_product_stock_proto_rawDescData []byte
)

func file_protos_store_v1_product_stock_proto_rawDescGZIP() []byte {
	file_protos_store_v1_product_stock_proto_rawDescOnce.Do(func() {
		file_protos_store_v1_product_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_store_v1_product_stock_proto_rawDesc), len(file_protos_store_v1_product_stock_proto_rawDesc)))
	})
	return file_protos_store_v1_product_stock_proto_rawDescData
}

var file_protos_store_v1_product_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_store_v1_product_stock_proto_goTypes = []any{
	(*ProductStockMain)(nil),    // 0: store.ProductStockMain
	(*ProductStockGetReq)(nil),  // 1: store.ProductStockGetReq
	(*ProductStockListReq)(nil), // 2: store.ProductStockListReq
	(*ProductStockListRep)(nil), // 3: store.ProductStockListRep
	(*ListParamsSt)(nil),        // 4: store.ListParamsSt
	(*PaginationInfoSt)(nil),    // 5: store.PaginationInfoSt
}
var file_protos_store_v1_product_stock_proto_depIdxs = []int32{
	4, // 0: store.ProductStockListReq.list_params:type_name -> store.ListParamsSt
	5, // 1: store.ProductStockListRep.pagination_info:type_name -> store.PaginationInfoSt
	0, // 2: store.ProductStockListRep.results:type_name -> store.ProductStockMain
	2, // 3: store.ProductStock.List:input_type -> store.ProductStockListReq
	1, // 4: store.ProductStock.Get:input_type -> store.ProductStockGetReq
	3, // 5: store.ProductStock.List:output_type -> store.ProductStockListRep
	0, // 6: store.ProductStock.Get:output_type -> store.ProductStockMain
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_store_v1_product_stock_proto_init() }
func file_protos_store_v1_product_stock_proto_init() {
	if File_protos_store_v1_product_stock_proto != nil {
		return
	}
	file_protos_store_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_store_v1_product_stock_proto_rawDesc), len(file_protos_store_v1_product_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_store_v1_product_stock_proto_goTypes,
		DependencyIndexes: file_protos_store_v1_product_stock_proto_depIdxs,
		MessageInfos:      file_protos_store_v1_product_stock_proto_msgTypes,
	}.Build()
	File_protos_store_v1_product_stock_proto = out.File
	file_protos_store_v1_product_stock_proto_goTypes = nil
	file_protos_store_v1_product_stock_proto_depIdxs = nil
}
