// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CityClient is the client API for City service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CityClient interface {
	List(ctx context.Context, in *CityListReq, opts ...grpc.CallOption) (*CityListRep, error)
	Get(ctx context.Context, in *CityGetReq, opts ...grpc.CallOption) (*CityMain, error)
}

type cityClient struct {
	cc grpc.ClientConnInterface
}

func NewCityClient(cc grpc.ClientConnInterface) CityClient {
	return &cityClient{cc}
}

func (c *cityClient) List(ctx context.Context, in *CityListReq, opts ...grpc.CallOption) (*CityListRep, error) {
	out := new(CityListRep)
	err := c.cc.Invoke(ctx, "/product.City/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityClient) Get(ctx context.Context, in *CityGetReq, opts ...grpc.CallOption) (*CityMain, error) {
	out := new(CityMain)
	err := c.cc.Invoke(ctx, "/product.City/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CityServer is the server API for City service.
// All implementations must embed UnimplementedCityServer
// for forward compatibility
type CityServer interface {
	List(context.Context, *CityListReq) (*CityListRep, error)
	Get(context.Context, *CityGetReq) (*CityMain, error)
	mustEmbedUnimplementedCityServer()
}

// UnimplementedCityServer must be embedded to have forward compatible implementations.
type UnimplementedCityServer struct {
}

func (UnimplementedCityServer) List(context.Context, *CityListReq) (*CityListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCityServer) Get(context.Context, *CityGetReq) (*CityMain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCityServer) mustEmbedUnimplementedCityServer() {}

// UnsafeCityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CityServer will
// result in compilation errors.
type UnsafeCityServer interface {
	mustEmbedUnimplementedCityServer()
}

func RegisterCityServer(s grpc.ServiceRegistrar, srv CityServer) {
	s.RegisterService(&City_ServiceDesc, srv)
}

func _City_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CityListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.City/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServer).List(ctx, req.(*CityListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _City_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CityGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.City/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServer).Get(ctx, req.(*CityGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// City_ServiceDesc is the grpc.ServiceDesc for City service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var City_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.City",
	HandlerType: (*CityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _City_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _City_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "city.proto",
}
